{
    'name': 'My Module',
    'version': '1.0',
    'category': 'Extra Tools',
    'summary': 'Test module',
    'description': 'Test module for addons path',
    'depends': ['base'],
    'data': [],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
    'application': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
