from .my_model import *
from .my_custom_module import *
from .school_student import *
from .school_teacher import *
from .school_group import *
from .course import *
from .document import *
from .sale_order  import *
from .uic_product import *
from .product_line import *
from .custom_products import *
from productpriceupdate_wizard import *
from sales_report__wizard import *
from contactexport_wizard import *
from task import *